/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package core.view;

import core.quanly.service.impl.KMSanPhamImpl;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import core.quanly.service.KhuyenMaiService;
import core.quanly.service.impl.KhuyenMaiImpl;
import core.quanly.viewmodel.KhuyenMaiResponse;
import domainmodels.KhuyenMai;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import core.quanly.service.KMSanPhamService;
import core.quanly.viewmodel.KMChiTietSPResponse;
import core.quanly.viewmodel.KMSanphamDangKmReponse;
import core.quanly.viewmodel.KMSanphamReponse;
import domainmodels.ChiTietSP;
import domainmodels.ChiTietSPKhuyenMai;
import java.math.BigDecimal;
import java.text.DateFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 *
 * @author thangncph26123
 */
public class ViewKhuyenMai extends javax.swing.JPanel {

    /**
     * Creates new form ViewKhuyenMai
     */
    DefaultTableModel modelsanpham = new DefaultTableModel();
    DefaultTableModel modelkhuyenmai = new DefaultTableModel();
    DefaultTableModel modelsanphamdangkm = new DefaultTableModel();
    DefaultComboBoxModel modelloaikhuyenmai;
    KMSanPhamService sanPhamService = new KMSanPhamImpl();
    KhuyenMaiService khuyenMaiService = new KhuyenMaiImpl();
    List<KhuyenMaiResponse> listkhuyenmai = new ArrayList<>();
    List<KMChiTietSPResponse> listsanpham = new ArrayList<>();
    List<KMSanphamDangKmReponse> listsanpham2 = new ArrayList<>();
    boolean selected = false;
    int count = 0;

    public ViewKhuyenMai() {
        initComponents();
        modelsanpham = (DefaultTableModel) tblsanpham.getModel();
        modelkhuyenmai = (DefaultTableModel) tblkhuyenmai.getModel();
        modelsanphamdangkm = (DefaultTableModel) tblsanpham2.getModel();
        FillToSanPham();
        listkhuyenmai = khuyenMaiService.GetKhuyenMaiDangDienRa();
        FillToKhuyenMai(listkhuyenmai);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jdcbatdau = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jdcketthuc = new com.toedter.calendar.JDateChooser();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtMoTa = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        btnsua = new javax.swing.JButton();
        btnthem = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblsanpham = new javax.swing.JTable();
        chkselectedall = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        txtgiamgia = new javax.swing.JTextField();
        cobgiamgia = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txttenkm = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtmakm = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tbpkhuyenmai = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblkhuyenmai = new javax.swing.JTable();
        txttim = new javax.swing.JTextField();
        cobtrangthaikhuyenmai = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblsanpham2 = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1292, 784));
        setMinimumSize(new java.awt.Dimension(1292, 784));
        setPreferredSize(new java.awt.Dimension(1292, 784));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Chương trình khuyến mại"));
        jPanel2.setPreferredSize(new java.awt.Dimension(1292, 784));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMaximumSize(new java.awt.Dimension(1209, 468));
        jPanel3.setMinimumSize(new java.awt.Dimension(1209, 468));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Thời gian sử dụng"));

        jdcbatdau.setDateFormatString("dd-MM-yyyy hh:mm:SS");
        jdcbatdau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jdcbatdauMouseClicked(evt);
            }
        });
        jdcbatdau.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                jdcbatdauCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        jdcbatdau.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jdcbatdauKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jdcbatdauKeyReleased(evt);
            }
        });

        jLabel5.setText("Thời gian bắt đầu giảm giá");

        jLabel7.setText("Thời gian kết thúc giảm giá");

        jdcketthuc.setDateFormatString("dd-MM-yyyy hh:mm:SS");

        txtMoTa.setColumns(20);
        txtMoTa.setRows(5);
        jScrollPane3.setViewportView(txtMoTa);

        jLabel8.setText("Mô tả");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jdcketthuc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                                .addComponent(jdcbatdau, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel8))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdcbatdau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdcketthuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnsua.setBackground(new java.awt.Color(153, 204, 255));
        btnsua.setText("Sửa");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        btnthem.setBackground(new java.awt.Color(153, 204, 255));
        btnthem.setText("Thêm");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Thiết lập khuyến mại"));

        tblsanpham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Select", "Mã sản phẩm", "Tên sản phẩm", "Hãng", "Màu sắc", "Size", "Chất liệu"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblsanpham.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblsanpham.getTableHeader().setReorderingAllowed(false);
        tblsanpham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblsanphamMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblsanpham);
        if (tblsanpham.getColumnModel().getColumnCount() > 0) {
            tblsanpham.getColumnModel().getColumn(1).setResizable(false);
            tblsanpham.getColumnModel().getColumn(2).setResizable(false);
            tblsanpham.getColumnModel().getColumn(3).setResizable(false);
            tblsanpham.getColumnModel().getColumn(5).setResizable(false);
        }

        chkselectedall.setText("Select all");
        chkselectedall.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkselectedallMouseClicked(evt);
            }
        });
        chkselectedall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkselectedallActionPerformed(evt);
            }
        });

        jLabel4.setText("Mức giảm giá");

        cobgiamgia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Giam theo %", "Giam theo số tiền" }));

        jLabel3.setText("Hình thức giảm giá");

        jLabel2.setText("Tạo chương trình khuyến mại");

        jLabel1.setText("Tạo mã khuyến mại");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txttenkm, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                                    .addComponent(txtmakm, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(43, 43, 43))
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addComponent(cobgiamgia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGap(20, 20, 20)))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(90, 90, 90)))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtgiamgia))))
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(chkselectedall))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtmakm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txttenkm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cobgiamgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtgiamgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkselectedall)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnthem, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnsua, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnsua)
                            .addComponent(btnthem))))
                .addContainerGap())
        );

        jPanel5.getAccessibleContext().setAccessibleDescription("");

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dánh sách khuyến mại"));

        tblkhuyenmai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã khuyến mại", "Tên khuyến mại", "Hình thức giảm giá", "Giảm giá", "Ngày bắt đầu", "Ngày kết thúc"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblkhuyenmai.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblkhuyenmai.getTableHeader().setReorderingAllowed(false);
        tblkhuyenmai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblkhuyenmaiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblkhuyenmai);
        if (tblkhuyenmai.getColumnModel().getColumnCount() > 0) {
            tblkhuyenmai.getColumnModel().getColumn(0).setResizable(false);
            tblkhuyenmai.getColumnModel().getColumn(1).setResizable(false);
            tblkhuyenmai.getColumnModel().getColumn(2).setResizable(false);
            tblkhuyenmai.getColumnModel().getColumn(3).setResizable(false);
            tblkhuyenmai.getColumnModel().getColumn(4).setResizable(false);
            tblkhuyenmai.getColumnModel().getColumn(5).setResizable(false);
        }

        txttim.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txttimCaretUpdate(evt);
            }
        });
        txttim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttimActionPerformed(evt);
            }
        });

        cobtrangthaikhuyenmai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đang diễn ra", "Sắp diễn ra", "Đã hết hạn" }));
        cobtrangthaikhuyenmai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cobtrangthaikhuyenmaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(txttim, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cobtrangthaikhuyenmai, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1176, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttim, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cobtrangthaikhuyenmai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tbpkhuyenmai.addTab("Danh sách khuyến mại", jPanel6);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        tblsanpham2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Hãng ", "Màu sắc", "Size", "Chất liệu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblsanpham2.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tblsanpham2);
        if (tblsanpham2.getColumnModel().getColumnCount() > 0) {
            tblsanpham2.getColumnModel().getColumn(0).setResizable(false);
            tblsanpham2.getColumnModel().getColumn(1).setResizable(false);
            tblsanpham2.getColumnModel().getColumn(2).setResizable(false);
            tblsanpham2.getColumnModel().getColumn(3).setResizable(false);
            tblsanpham2.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1186, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbpkhuyenmai.addTab("Danh sách sản phẩm đã áp dụng khuyến mại", jPanel7);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tbpkhuyenmai)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbpkhuyenmai, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 774, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblkhuyenmaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblkhuyenmaiMouseClicked
        int index = tblkhuyenmai.getSelectedRow();
        KhuyenMaiResponse khuyenMaiResponse = listkhuyenmai.get(index);
        if (index >= 0) {
            txtmakm.setText(khuyenMaiResponse.getMakm());
            txttenkm.setText(khuyenMaiResponse.getTenkm());
            txtgiamgia.setText(khuyenMaiResponse.getGiaTri() + "");
            DateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy hh:mm:ss");
            jdcbatdau.setDate(khuyenMaiResponse.getNgayBatDau());
            jdcketthuc.setDate(khuyenMaiResponse.getNgayKetThuc());
            if (khuyenMaiResponse.getLoaiKhuyenMai().equals(0)) {
                cobgiamgia.setSelectedIndex(0);
            } else {
                cobgiamgia.setSelectedIndex(1);
            }
        }
        tbpkhuyenmai.setSelectedIndex(1);
        listsanpham2 = khuyenMaiService.GetAllSanPhamDangApDung(khuyenMaiResponse.getIdkm());
        System.out.println(listsanpham2);
        FillToSanPhamDangKM(listsanpham2);
    }//GEN-LAST:event_tblkhuyenmaiMouseClicked

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        try {
            if (txtmakm.getText().trim().isEmpty()
                    || txttenkm.getText().trim().isEmpty()
                    || txtgiamgia.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Không được để trống");
                return;
            }
            if (cobgiamgia.getSelectedIndex() == 0) {
                if (Double.parseDouble(txtgiamgia.getText().trim()) < 0 || Double.parseDouble(txtgiamgia.getText().trim()) > 100) {
                    JOptionPane.showMessageDialog(this, "Giá trị phần trăm phải > 0 và <= 100");
                    return;
                }
            }
            if (Double.parseDouble(txtgiamgia.getText().trim()) < 0) {
                JOptionPane.showMessageDialog(this, "Giá trị giảm giá không được âm");
                return;
            }

            KhuyenMai khuyenMai = new KhuyenMai();
            khuyenMai.setMa(txtmakm.getText().trim());
            khuyenMai.setTen(txttenkm.getText().trim());
            khuyenMai.setLoaiKhuyenMai(cobgiamgia.getSelectedIndex());
            khuyenMai.setGiaTri(Double.parseDouble(txtgiamgia.getText().trim()));
            khuyenMai.setNgayBatDau(jdcbatdau.getDate());
            khuyenMai.setNgayKetThuc(jdcketthuc.getDate());
            khuyenMai.setMoTa(txtMoTa.getText().trim());
            khuyenMaiService.saveOrUpdateKM(khuyenMai);

            List<KMChiTietSPResponse> listSelected = GetSelected();
            for (KMChiTietSPResponse xx : listSelected) {
                ChiTietSPKhuyenMai chiTietSPKhuyenMai = new ChiTietSPKhuyenMai();
                ChiTietSP chiTietSP = khuyenMaiService.findChiTietSpById(xx.getId());
                chiTietSPKhuyenMai.setChiTietSPId(chiTietSP);
                chiTietSPKhuyenMai.setKhuyenMaiId(khuyenMai);
                chiTietSPKhuyenMai.setDonGia(chiTietSP.getGiaBan());
                chiTietSPKhuyenMai.setTrangThai(0);
                if (khuyenMai.getLoaiKhuyenMai() == 0) {
                    BigDecimal donGiaConLai = chiTietSP.getGiaBan().subtract(chiTietSP.getGiaBan().multiply(new BigDecimal(khuyenMai.getGiaTri()).divide(new BigDecimal(100))));
                    chiTietSPKhuyenMai.setDonGiaConLai(donGiaConLai);
                } else {
                    BigDecimal donGiaConLai = chiTietSP.getGiaBan().subtract(new BigDecimal(khuyenMai.getGiaTri()));
                    chiTietSPKhuyenMai.setDonGiaConLai(donGiaConLai);
                }
                khuyenMaiService.saveOrUpdate(chiTietSPKhuyenMai);
            }

            FillToSanPham();
            listkhuyenmai = khuyenMaiService.getAllResponseKhuyenMai();
            FillToKhuyenMai(listkhuyenmai);
            JOptionPane.showMessageDialog(this, "Tạo chương trình khuyến mại thành công");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnthemActionPerformed

    private void txttimCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txttimCaretUpdate
        String input = txttim.getText();
        if (cobtrangthaikhuyenmai.getSelectedIndex() == 0) {
            listkhuyenmai = khuyenMaiService.FindMaOrTenByInputDangDienRa(input);
            FillToKhuyenMai(listkhuyenmai);            
        } else if (cobtrangthaikhuyenmai.getSelectedIndex() == 1) {
            listkhuyenmai = khuyenMaiService.FindMaOrTenByInputSapDienRa(input);
            FillToKhuyenMai(listkhuyenmai);            
        } else {
            listkhuyenmai = khuyenMaiService.FindMaOrTenByInputDaDienRa(input);
            FillToKhuyenMai(listkhuyenmai);            
        }       
    }//GEN-LAST:event_txttimCaretUpdate

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        try {
            int index = tblkhuyenmai.getSelectedRow();
            if (index == -1) {
                JOptionPane.showMessageDialog(this, "ban chua Chọn dòng");
                return;
            }
            KhuyenMai khuyenMai = new KhuyenMai();
            khuyenMai.setId(listkhuyenmai.get(index).getIdkm());
            System.out.println(khuyenMai.getId());
            khuyenMai.setMa(txtmakm.getText().trim());
            khuyenMai.setTen(txttenkm.getText().trim());
            khuyenMai.setLoaiKhuyenMai(cobgiamgia.getSelectedIndex());
            khuyenMai.setGiaTri(Double.parseDouble(txtgiamgia.getText().trim()));
            khuyenMai.setNgayBatDau(jdcbatdau.getDate());
            khuyenMai.setNgayKetThuc(jdcketthuc.getDate());
            khuyenMaiService.saveOrUpdateKM(khuyenMai);
            List<KMChiTietSPResponse> listSelected = GetSelected();
            for (KMChiTietSPResponse xx : listSelected) {
                ChiTietSPKhuyenMai chiTietSPKhuyenMai = new ChiTietSPKhuyenMai();
                ChiTietSP chiTietSP = khuyenMaiService.findChiTietSpById(xx.getId());
                chiTietSPKhuyenMai.setChiTietSPId(chiTietSP);
                chiTietSPKhuyenMai.setKhuyenMaiId(khuyenMai);
                chiTietSPKhuyenMai.setDonGia(chiTietSP.getGiaBan());
                chiTietSPKhuyenMai.setTrangThai(0);
                if (khuyenMai.getLoaiKhuyenMai() == 0) {
                    BigDecimal donGiaConLai = chiTietSP.getGiaBan().subtract(chiTietSP.getGiaBan().multiply(new BigDecimal(khuyenMai.getGiaTri()).divide(new BigDecimal(100))));
                    chiTietSPKhuyenMai.setDonGiaConLai(donGiaConLai);
                } else {
                    BigDecimal donGiaConLai = chiTietSP.getGiaBan().subtract(new BigDecimal(khuyenMai.getGiaTri()));
                    chiTietSPKhuyenMai.setDonGiaConLai(donGiaConLai);
                }
                khuyenMaiService.saveOrUpdate(chiTietSPKhuyenMai);
            }
            FillToSanPham();
            listkhuyenmai = khuyenMaiService.getAllResponseKhuyenMai();
            FillToKhuyenMai(listkhuyenmai);
            JOptionPane.showMessageDialog(this, "Sửa chương trình khuyến mại thành công");
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnsuaActionPerformed

    private void chkselectedallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkselectedallActionPerformed
        if (!selected) {
            for (int i = 0; i < listsanpham.size(); i++) {
                tblsanpham.setValueAt(true, i, 0);
            }
            selected = true;
        } else {
            for (int i = 0; i < listsanpham.size(); i++) {
                tblsanpham.setValueAt(false, i, 0);
            }
            selected = false;
        }
    }//GEN-LAST:event_chkselectedallActionPerformed

    private void chkselectedallMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkselectedallMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_chkselectedallMouseClicked

    private void tblsanphamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblsanphamMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblsanphamMouseClicked

    private void jdcbatdauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jdcbatdauMouseClicked
    }//GEN-LAST:event_jdcbatdauMouseClicked

    private void jdcbatdauCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jdcbatdauCaretPositionChanged
    }//GEN-LAST:event_jdcbatdauCaretPositionChanged

    private void jdcbatdauKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jdcbatdauKeyReleased
    }//GEN-LAST:event_jdcbatdauKeyReleased

    private void jdcbatdauKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jdcbatdauKeyPressed
    }//GEN-LAST:event_jdcbatdauKeyPressed

    private void cobtrangthaikhuyenmaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cobtrangthaikhuyenmaiActionPerformed
        if (cobtrangthaikhuyenmai.getSelectedIndex() == 0) {
            
            btnsua.setEnabled(true);
            btnthem.setEnabled(true);
            listkhuyenmai = khuyenMaiService.GetKhuyenMaiDangDienRa();
            FillToKhuyenMai(listkhuyenmai);
            
        } else if (cobtrangthaikhuyenmai.getSelectedIndex() == 1) {
            btnsua.setEnabled(true);
            btnthem.setEnabled(true);
            listkhuyenmai = khuyenMaiService.GetKhuyenMaiSapDienRa();
            FillToKhuyenMai(listkhuyenmai);
           
        } else {
            btnsua.setEnabled(false);
            btnthem.setEnabled(false);
            listkhuyenmai = khuyenMaiService.GetKhuyenMaiDaDienRa();
            FillToKhuyenMai(listkhuyenmai);
        }
    }//GEN-LAST:event_cobtrangthaikhuyenmaiActionPerformed

    private void txttimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttimActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.JCheckBox chkselectedall;
    private javax.swing.JComboBox<String> cobgiamgia;
    private javax.swing.JComboBox<String> cobtrangthaikhuyenmai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private com.toedter.calendar.JDateChooser jdcbatdau;
    private com.toedter.calendar.JDateChooser jdcketthuc;
    private javax.swing.JTable tblkhuyenmai;
    private javax.swing.JTable tblsanpham;
    private javax.swing.JTable tblsanpham2;
    private javax.swing.JTabbedPane tbpkhuyenmai;
    private javax.swing.JTextArea txtMoTa;
    private javax.swing.JTextField txtgiamgia;
    private javax.swing.JTextField txtmakm;
    private javax.swing.JTextField txttenkm;
    private javax.swing.JTextField txttim;
    // End of variables declaration//GEN-END:variables

    private void FillToSanPham() {
        modelsanpham.setRowCount(0);
        listsanpham = khuyenMaiService.getAllChiTietSP();
        for (KMChiTietSPResponse xx : listsanpham) {
            modelsanpham.addRow(xx.toDaTaRow());
        }
    }

    private void FillToKhuyenMai(List<KhuyenMaiResponse> list) {
        modelkhuyenmai.setRowCount(0);
        for (KhuyenMaiResponse x : list) {
            modelkhuyenmai.addRow(x.ToDaTa1());
        }
    }

    private void FillToSanPhamDangKM(List<KMSanphamDangKmReponse> list) {
        modelsanphamdangkm.setRowCount(0);
        for (KMSanphamDangKmReponse xx : list) {
            Object[] row = new Object[]{xx.getMa(), xx.getTen(), xx.getTenhang(), xx.getMausac(), xx.getKichthuoc(), xx.getChatlieu()};
            modelsanphamdangkm.addRow(row);
        }
    }

    private List<KMChiTietSPResponse> GetSelectedAll() {
        listsanpham = khuyenMaiService.getAllChiTietSP();
        for (int i = 0; i < listsanpham.size(); i++) {
            String id = tblsanpham.getValueAt(i, 0).toString();
            String ma = tblsanpham.getValueAt(i, 1).toString();
            String ten = tblsanpham.getValueAt(i, 2).toString();
            String hang = tblsanpham.getValueAt(i, 3).toString();
            String mausac = tblsanpham.getValueAt(i, 4).toString();
            String kichthuoc = tblsanpham.getValueAt(i, 5).toString();
            String chatlieu = tblsanpham.getValueAt(i, 6).toString();
            tblsanpham.setValueAt(true, i, 0);
            KMChiTietSPResponse chiTietSPResponse = new KMChiTietSPResponse(id, ma, ten, hang, mausac, kichthuoc, chatlieu);
            List<KMChiTietSPResponse> listselectall = new ArrayList<>();
            listselectall.add(chiTietSPResponse);
        }
        return listsanpham;
    }

    private List<KMChiTietSPResponse> GetSelected() {
        List<KMChiTietSPResponse> listselected = new ArrayList<>();
        listsanpham = khuyenMaiService.getAllChiTietSP();
        for (int i = 0; i < listsanpham.size(); i++) {
            boolean check = Boolean.valueOf(tblsanpham.getValueAt(i, 0).toString());
            System.out.println(check);
            if (check) {
                listselected.add(listsanpham.get(i));
            }
        }
        return listselected;
    }
}
